steps:
 - name: 'ubuntu'
   args: ['echo','Hello boi 1']
   waitFor: ['step 2']

 - name: 'ubuntu'
   args: ['echo','Hello boi 2']
   id: 'step2'

 - name: 'ubuntu'
   args: ['echo','Hello boi 3']
   waitFor: ['step2'] 

options:
 logging: CLOUD_LOGGING_ONLY